inherits:
  - strictness_high

ignore-paths:
  - build
  - trepr/bla.py

pep257:
  run: true
  disable:
    - D107
    - D203
    - D212
    - D213

pycodestyle:
  disable:
    - E203
    - W503
  enable:
    - W504

pyroma:
  run: true

pyflakes:
  run: true
  disable:
    - F401
    - F403

pylint:
  options:
    max-attributes: 20
    max-module-lines: 1300
  disable:
    - invalid-name
    - import-error
    - unused-import
    - wildcard-import

