inherits:
  - strictness_high

ignore-paths:
  - trepr/bla.py

pep257:
  run: true
  disable:
    - D107
    - D203
    - D212
    - D213

pyroma:
  run: true

pyflakes:
  run: true
  disable:
    - F401
    - F403

pylint:
  options:
    max-attributes: 20
  disable:
    - invalid-name
    - import-error
    - unused-import
    - wildcard-import

