---

format:
  type: ASpecD recipe
  version: 0.1.0

datasets:
  - /home/jara/Dokumente/python/Daten/messung17/

tasks:
  - kind: processing
    type: PretriggerOffsetCompensation
  - kind: processing
    type: Averaging
    properties:
      parameters:
        dimension: 0
        range: [4.e-7, 6.e-7]
        unit: axis
  - kind: analysis
    type: FittingAnalysis
    properties:
      parameters: /home/jara/Dokumente/python/trepr/trepr/fitpy-input.yaml
    apply_to:
      - /home/jara/Dokumente/python/Daten/messung17/
    result: fit_result
  - kind: processing
    type: Normalise
    parameters:
      - type: area
    apply_to:
      - /home/jara/Dokumente/python/Daten/messung17/
      - fit_result
  - kind: multiplot
    type: MultiLinePlot
    apply_to:
      - /home/jara/Dokumente/python/Daten/messung17/
      - fit_result
    properties:
      parameters:
        colors: ['#6600CC', '#FF3333']
      filename: /home/jara/Dokumente/python/trepr/trepr/plot.pdf